const express = require('express')
const projectController = require('../Controller/ProjectController')
const Project = require('../Model/Project')
const projectRouter = express.Router()
projectRouter.get('/', projectController.getProjects)
projectRouter.get('/detail/:id', projectController.getDetail)
projectRouter.get('/livestream', projectController.getLivestream)
projectRouter.get('/:category', projectController.getProjectByCategory)
projectRouter.post('/add', projectController.addProject)
projectRouter.post('/add-stream', projectController.addStream)
projectRouter.delete('/delete/:id/:public_id', projectController.deleteProject)
projectRouter.delete('/delete-livestream/:id/:public_id', projectController.deleteLivestream)
projectRouter.post('/edit/:id', projectController.editProject)
projectRouter.post('/edit-livestream/:id', projectController.editLivestream)
module.exports = projectRouter